# This file was generated by GoReleaser. DO NOT EDIT.
class Prana < Formula
  desc "Golang Database Management and Code Generation"
  homepage "https://github.com/phogolabs/prana"
  version "1.0.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/phogolabs/prana/releases/download/v1.0.0-rc1/prana_1.0.0-rc1_darwin_amd64.tar.gz"
    sha256 "d4b8c0b1574326664694421e36724217ea51ac906b4b56e1f35a1890cae6f687"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/phogolabs/prana/releases/download/v1.0.0-rc1/prana_1.0.0-rc1_linux_amd64.tar.gz"
      sha256 "be1ed9c6c2669eb7722c7b91a94be6c7b168d65053a5cdf0d58031ab41f07167"
    end
  end

  def install
    bin.install "prana"
  end

  test do
    system "#{bin}/prana -v"
  end
end
