# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strava < Formula
  desc "Vendoring made easy"
  homepage "https://github.com/phogolabs/strava"
  version "0.0.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phogolabs/strava/releases/download/v0.0.3/strava_0.0.3_darwin_amd64.tar.gz"
      sha256 "b819519bebe25aa373a2ae558dd162c20f7040e797f4b83da6c903c57046b5d0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/phogolabs/strava/releases/download/v0.0.3/strava_0.0.3_darwin_arm64.tar.gz"
      sha256 "3ec17c13961cec2c7ec594fb49801ec10139e79c0f9cae6e9c25fb5b2bacac9f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/phogolabs/strava/releases/download/v0.0.3/strava_0.0.3_linux_amd64.tar.gz"
      sha256 "1028b3d6338fea9242756f4730c2b2019a049f80af1f09ffab2cdae68732df34"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phogolabs/strava/releases/download/v0.0.3/strava_0.0.3_linux_arm64.tar.gz"
      sha256 "eb57d889a6284a5ea3742af446754cd5335670342ebc86282728130d646b1bfa"
    end
  end

  def install
    bin.install "strava"
  end

  test do
    system "#{bin}/strava -v"
  end
end
