# This file was generated by GoReleaser. DO NOT EDIT.
class Stride < Formula
  desc "OpenAPI viewer, editor, generator, validator and mocker"
  homepage "https://github.com/phogolabs/stride"
  version "0.0.2-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/phogolabs/stride/releases/download/v0.0.2-rc1/stride_0.0.2-rc1_darwin_amd64.tar.gz"
    sha256 "71e3aadeae9d985eb9eb4032f28fafa31f425fdbe4145cc586e9226c0c3ca4cf"
  elsif OS.linux?
  end

  def install
    bin.install "stride"
  end

  test do
    system "#{bin}/stride -v"
  end
end
