# This file was generated by GoReleaser. DO NOT EDIT.
class Stride < Formula
  desc "Golang Database Management and Code Generation"
  homepage "https://github.com/phogolabs/prana"
  version "1.0.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/phogolabs/prana/releases/download/v1.0.0-rc1/prana_1.0.0-rc1_darwin_amd64.tar.gz"
    sha256 "b566dfd2bb87083dd2e0fcb33649b6851091e1a0c0e038a5e5d73aa5f261c9eb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/phogolabs/prana/releases/download/v1.0.0-rc1/prana_1.0.0-rc1_linux_amd64.tar.gz"
      sha256 "92c8a08a37f4aba27d2df461328684d93fd9f93d58f7cbce6e673b609a7eff80"
    end
  end

  def install
    bin.install "prana"
  end

  test do
    system "#{bin}/prana -v"
  end
end
