# This file was generated by GoReleaser. DO NOT EDIT.
cask "prana" do
  version "1.0.0-rc13"

  on_macos do
    on_intel do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_darwin_amd64.tar.gz"
      sha256 "d5fe9ee8a7144a3f0472c4cdc7123e50621a15fe973afa4cd555f40fe8b63f98"
    end
    on_arm do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_darwin_arm64.tar.gz"
      sha256 "52adfb0f91b453d755c4adb3ba6b2c6495813d122dc6836d0efbb5004cf06655"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_linux_amd64.tar.gz"
      sha256 "99051790a679eba0cb595229bedf8121d7ca0f66d55404c801d52364d16e0c81"
    end
    on_arm do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_linux_arm64.tar.gz"
      sha256 "fc750c0c0f00a6b9e3a9f1ba6babe6a01baf9f55c57b39ec1980d7d1b1ace836"
    end
  end

  name "prana"
  desc "Golang Database Management and Code Generation"
  homepage "https://github.com/phogolabs/prana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prana"

  # No zap stanza required

end
