# This file was generated by GoReleaser. DO NOT EDIT.
cask "prana" do
  version "1.0.0-rc12"

  on_macos do
    on_intel do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_darwin_amd64.tar.gz"
      sha256 "3cfc9928285d0ba177f385becc3c82f2dea34a526b9e0b7ca61c971516646b31"
    end
    on_arm do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_darwin_arm64.tar.gz"
      sha256 "07fa9ca1ac57eb1bcdd5094d7826f247947e2a342ac2ca78e2350cb5b447ef06"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_linux_amd64.tar.gz"
      sha256 "3380d730f385ec9659d1aef684b654c9e116adb831ea3d5e62b165409436069c"
    end
    on_arm do
      url "https://github.com/phogolabs/prana/releases/download/v#{version}/prana_#{version}_linux_arm64.tar.gz"
      sha256 "cded0b782552690bdc5f1ff00ee7ca638692d3847171ac863ca8d8dcc8a6c71b"
    end
  end

  name "prana"
  desc "Golang Database Management and Code Generation"
  homepage "https://github.com/phogolabs/prana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prana"

  # No zap stanza required

end
